// <auto-generated />
using System;
using ConventionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConventionApi.Migrations
{
    [DbContext(typeof(ConventionApiContext))]
    [Migration("20210620183849_AddTalkAndRegistration")]
    partial class AddTalkAndRegistration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConventionApi.Model.Convention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Convention");
                });

            modelBuilder.Entity("ConventionApi.Model.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TalkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TalkId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("ConventionApi.Model.Talk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConventionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConventionId");

                    b.ToTable("Talk");
                });

            modelBuilder.Entity("ConventionApi.Model.Registration", b =>
                {
                    b.HasOne("ConventionApi.Model.Talk", "Talk")
                        .WithMany()
                        .HasForeignKey("TalkId");

                    b.Navigation("Talk");
                });

            modelBuilder.Entity("ConventionApi.Model.Talk", b =>
                {
                    b.HasOne("ConventionApi.Model.Convention", "Convention")
                        .WithMany()
                        .HasForeignKey("ConventionId");

                    b.Navigation("Convention");
                });
#pragma warning restore 612, 618
        }
    }
}
